const restaurants = [
    { name: "Budget Bites Cafe", priceRange: "$", cuisine: "Cafe", distance: 1, rating: 4.5 },
    { name: "Spicy Delights", priceRange: "$$", cuisine: "Indian", distance: 5, rating: 4.0 },
    { name: "Sushi Haven", priceRange: "$$$", cuisine: "Japanese", distance: 3, rating: 4.8 },
    { name: "Pasta Palace", priceRange: "$$", cuisine: "Italian", distance: 2, rating: 3.9 },
    { name: "Burger Bliss", priceRange: "$", cuisine: "Fast Food", distance: 4, rating: 4.2 },
    { name: "Alto Vino", priceRange: "$$", cuisine: "Italian", distance: 7, rating: 4.0 },
    { name: "Paasha", priceRange: "$$$", cuisine: "Indian", distance: 8, rating: 4.2 },
    { name: "Spice Kitchen", priceRange: "$$", cuisine: "Asian", distance: 6, rating: 4.2 },
    { name: "Ukiyo", priceRange: "$$$", cuisine: "Japanese", distance: 9, rating: 4.5 },
    { name: "Aasmana", priceRange: "$$$", cuisine: "Indian", distance: 10, rating: 4.3 },
    { name: "Vaishali", priceRange: "$", cuisine: "South Indian", distance: 3, rating: 4.6 },
    { name: "Cafe GoodLuck", priceRange: "$", cuisine: "Parsi", distance: 5, rating: 4.5 },
    { name: "Chingari", priceRange: "$$$", cuisine: "Indian", distance: 8, rating: 4.4 },
    { name: "Savya Rasa", priceRange: "$$$", cuisine: "South Indian", distance: 6, rating: 4.7 },
    { name: "German Bakery", priceRange: "$$", cuisine: "Cafe", distance: 4, rating: 4.3 },
    { name: "Malaka Spice", priceRange: "$$$", cuisine: "Asian Fusion", distance: 7, rating: 4.6 },
    { name: "Baan Tao", priceRange: "$$$", cuisine: "Thai", distance: 9, rating: 4.5 },
    { name: "Arthur's Theme", priceRange: "$$", cuisine: "Continental", distance: 6, rating: 4.3 },
    { name: "The Flour Works", priceRange: "$$", cuisine: "European", distance: 5, rating: 4.4 },
    { name: "Indigo Delicatessen", priceRange: "$$", cuisine: "Modern Indian", distance: 7, rating: 4.2 },
    { name: "Fish Curry Rice", priceRange: "$$", cuisine: "Coastal", distance: 3, rating: 4.5 },
    { name: "Blue Nile", priceRange: "$$", cuisine: "Mughlai", distance: 6, rating: 4.3 },
    { name: "Biryani By Kilo", priceRange: "$$", cuisine: "Indian", distance: 4, rating: 4.2 },
    { name: "AB's Absolute Barbecues", priceRange: "$$", cuisine: "Barbecue", distance: 5, rating: 4.4 },
    { name: "The Village Rooftop", priceRange: "$$", cuisine: "Multi-Cuisine", distance: 8, rating: 4.1 }
];